const data = [
    {
      "Longitude": -58.381592,
      "Latitude": -34.603722,
      "City": "Buenos Aires",
      "State/Territory": "Buenos Aires",
      "Country": "Argentina",
      "Region": "South America",
      "Name of Organization": "Centro de Implementación de Politicas Públicas para la Equidad y el Crecimiento",
      "Website": "https://www.cippec.org/",
      "Total Members": 76,
      "Year Founded": 1991,
      "About Us": "CIPPEC is an independent, nonpartisan and non-profit organization that produces knowledge and offers recommendations to build better public policies. We promote policies to achieve a developed Argentina, more equitable, with equal opportunities and solid and effective public institutions. We want a just, democratic and inclusive society, in which all people can develop in freedom. "
    },
    {
      "Longitude": 149.128998,
      "Latitude": -35.282001,
      "City": "Canberra",
      "State/Territory": "New South Wales",
      "Country": "Australia",
      "Region": "Oceania",
      "Name of Organization": "Australian Centre for Federalism",
      "Website": "http://politicsir.cass.anu.edu.au/centres/acf",
      "Total Members": 16,
      "Year Founded": 1949,
      "About Us": "The mission of the Centre is to become Australia’s premier university-based centre for research on all aspects of federalism and multi-level governance, both in Australia and beyond."
    },
    {
      "Longitude": 144.946457,
      "Latitude": -37.840935,
      "City": "Melbourne",
      "State/Territory": "Victoria",
      "Country": "Australia",
      "Region": "Oceania",
      "Name of Organization": "International Association of Centers for Federal Studies/Centre for Comparative Constitutional Studies",
      "Website": "https://law.unimelb.edu.au/centres/cccs",
      "Total Members": 52,
      "Year Founded": 1910,
      "About Us": "CCCS aims to actively contribute to the debate on the Australian system of government, to promote understanding of constitutional concepts and to provide a public and specialist resource on constitutional and comparative constitutional issues. The Centre pursues these objectives through its activities; research, teaching, information exchange, provision of resources, consultancies and research collaboration."
    },
    {
      "Longitude": 115.857048,
      "Latitude": -31.953512,
      "City": "Perth",
      "State/Territory": "Western Australia",
      "Country": "Australia",
      "Region": "Oceania",
      "Name of Organization": "John Curtin Institute of Public Policy",
      "Website": "https://businesslaw.curtin.edu.au/our-research/centres-and-institutes/jcipp/",
      "Total Members": 17,
      "Year Founded": 1957,
      "About Us": "The JCIPP is a peak body for research, education and discussion in public policy and administration. It takes a multi-disciplinary approach to addressing challenges in this area reflecting their complexity as well as the unique capacity of universities to play a key role in addressing them. The Institute's mission is: To undertake high quality research of national and international significance on current and emerging public policy and governance issues; to provide relevant, quality and contemporary education tailored to public sector professionals; and to promote public debate and discussion on a range of current and emerging public policy issues."
    },
    {
      "Longitude": 11.400375,
      "Latitude": 47.259659,
      "City": "Innsbruck",
      "State/Territory": "Tyrol",
      "Country": "Austria",
      "Region": "Europe",
      "Name of Organization": "Institut für Föderalismus",
      "Website": "http://www.foederalismus.at/",
      "Total Members": 23,
      "Year Founded": 1941,
      "About Us": "In connection with the efforts of the federal states to strengthen federalism in Austria, the idea of establishing a scientific institute with a focus on federalism research was pursued in Tyrol and Vorarlberg. The institute contributes to spreading the idea of federalism among the population through extensive information activities. "
    },
    {
      "Longitude": 4.4035,
      "Latitude": 51.2199,
      "City": "Antwerp",
      "State/Territory": "Antwerpen",
      "Country": "Belgium",
      "Region": "Europe",
      "Name of Organization": "Research Group on Government and Law",
      "Website": "https://www.uantwerpen.be/en/research-groups/government-and-law/",
      "Total Members": 25,
      "Year Founded": 2001,
      "About Us": "The Research Programme Government and Law aims to explore the relation between law and government in a broad sense, embedded in a legal, political and social context. Central research questions concern the impact of legal, political and social evolutions on the legal concept of government, on the working and competences of public institutions, on fundamental principles such as democracy, rule of law and federalism, and on the protection of persons against government action. The program aims to present the University of Antwerp on a national and international level as a research centre of public law which transcends traditional branches of law and disciplines."
    },
    {
      "Longitude": -76.485954,
      "Latitude": 44.231172,
      "City": "Kingston",
      "State/Territory": "Ontario",
      "Country": "Canada",
      "Region": "North America",
      "Name of Organization": "Institute of Intergovernmental Relations",
      "Website": "https://www.queensu.ca/iigr/home",
      "Total Members": 14,
      "Year Founded": 1953,
      "About Us": "The Institute of Intergovernmental Relations at Queen's University is Canada's premier university-based centre for research on all aspects of federalism and intergovernmental relations, both in Canada and in countries around the world. Over the years, it has been a leader in contributing to public debate on issues such as national unity, Canada-Quebec relations, fiscal federalism, constitutional reform, and the social union. Located in and working closely with the School of Policy Studies, as well as a number of Faculty Associates in other departments at Queen's University, the Institute is interdisciplinary in orientation, drawing on the latest research in political science, economics, philosophy, law, and sociology; providing a neutral venue to encourage dialogue among federal and provincial officials, key decision-makers and prominent scholars concerning many of the issues and challenges confronting the country. "
    },
    {
      "Longitude": -73.5878,
      "Latitude": 45.5088,
      "City": "Montréal",
      "State/Territory": "Québec",
      "Country": "Canada",
      "Region": "North America",
      "Name of Organization": "Le Centre de recherche interdisciplinaire sur la diversité",
      "Website": "https://creqc.uqam.ca/",
      "Total Members": 19,
      "Year Founded": 2020,
      "About Us": "Canada Research Chair in Quebec and Canadian Studies within the Department of Political Science at The Université du Québec à Montréal"
    },
    {
      "Longitude": -75.695,
      "Latitude": 45.424721,
      "City": "Ottawa",
      "State/Territory": "Ontario",
      "Country": "Canada",
      "Region": "North America",
      "Name of Organization": "Forums of Federations",
      "Website": "http://www.forumfed.org/",
      "Total Members": 74,
      "Year Founded": 1935,
      "About Us": "Forum is the world's leading international network on decentralization and federalism. One of the fundamental challenges for democratic governance, in our time, is to assure that governments at different levels work together in an effective and accountable way. The Forum of FEderations focuses on that challenge. Our website--including its online library--offers the world's most comprehensive online resource on federalism and multilevel governance for both researchers and practitioners. "
    },
    {
      "Longitude": -75.695,
      "Latitude": 45.424721,
      "City": "Ottawa",
      "State/Territory": "Ontario",
      "Country": "Canada",
      "Region": "North America",
      "Name of Organization": "Federation of Canadian Municipalities",
      "Website": "https://www.fcm.ca/en",
      "Total Members": 125,
      "Year Founded": 1901,
      "About Us": "FCM has been the national voice of municipal government since 1901. Our members include more than 2,000 municipalities of all sizes, from Canada's cities and rural communities, to northern communitieis and 20 provincial and territorial municipal associations. Together, they represent more than 90 percent of all Canadians from coast to coast to coast. Municipal leaders from across Canada assemble each year to set FCM policy on key issues. Today, we advocate for municipalities to be sure their citizens' needs are reflected in federal policies and programs. Year after year, our work benefits every municipal government and taxpayer in Canada, and our programming delivers tools that help municipalities tackle local challenges. "
    },
    {
      "Longitude": 38.763611,
      "Latitude": 9.005401,
      "City": "Addis Ababa",
      "State/Territory": "Oromia",
      "Country": "Ethiopia",
      "Region": "Africa",
      "Name of Organization": "The Centre for Federalism and Governance Studies",
      "Website": "http://www.aau.edu.et/clgs/academics/center-for-federal-studies/",
      "Total Members": 12,
      "Year Founded": 1985,
      "About Us": "Centre for Federalism and Governance Studies is one of the three units within the college of Law and Governance. It is a teaching and research centre in the area of federalism and multilevel governance. The vision of the CFGS is to be the centre of excellence in federalism. The Centre aims to contribute towards strengthening good governance and the democratization process, promote unity in diversity, and enhance peace and development in Ethiopia. "
    },
    {
      "Longitude": 7.26608,
      "Latitude": 43.70313,
      "City": "Nice",
      "State/Territory": "Provence-Alpes-Côte d'Azur",
      "Country": "France",
      "Region": "Europe",
      "Name of Organization": "Centre International de Formation Européenne",
      "Website": "https://www.cife.eu/",
      "Total Members": 37,
      "Year Founded": 1954,
      "About Us": "CIFE is a private institution of higher education and research, founded in 1954 with its head office in Nice and branch offices in Berlin, Brussels and Istanbul. For more than 60 years, the Centre has been promoting the values of Europe, European integration and governance, multilingualism and student mobility through its European and international higher education programmes. "
    },
    {
      "Longitude": 9.73322,
      "Latitude": 52.37052,
      "City": "Hannover",
      "State/Territory": "Lower Saxony",
      "Country": "Germany",
      "Region": "Europe",
      "Name of Organization": "Deutsches Institut für Föderalismusforschung e. V.",
      "Website": "http://dif-serv.dif.uni-hannover.de/~dif/",
      "Total Members": 2,
      "Year Founded": 1966,
      "About Us": "The Institute for Federal Studies researches constitutional developments, in particular the relations among the federation, the states, and local government of the Federal Republic as well as federal structures emerging in the process of European integration and inselected states and regions of Europe and the world; documents as a research center and archive sources dealing with federalism research and with contemporary history of constitutional law; provides information about current developments of federalism in the Federal Republic of Germany, in member states of the European Union, and in more distant foreign countries; advises on questions of federalism and constitutional reforms by means of a dialogue focuesd on practical problems and creates as a result the preconditions for various expert activities in many parts of the world; cooperates with domestic and foreign research institutions; publishes the series \"Federalism Studies,\" \"Federalism Documents,\" and \"Das Grundgesetz. Dokumentation seiner Entstehung.\""
    },
    {
      "Longitude": 11.62916,
      "Latitude": 52.12773,
      "City": "Magdeburg",
      "State/Territory": "Saxony-Anhalt",
      "Country": "Germany",
      "Region": "Europe",
      "Name of Organization": "Comparative Federalism and Federation Research Committee of the International Political Science Association",
      "Website": "https://comparative-federalism.org/",
      "Total Members": 6,
      "Year Founded": 2021,
      "About Us": "RC28 facilitates the pursuit of political science research and scholarship on federalism and multilevel governance from a global comparative perspective. This includes the coneptual, theoretical, and empirical analysis of the origins, operations, and consequences of federal and quasi-federal structures of government, from both a positive and a normative approach. RC28's scope spans federal and confederal systems as well as unitary states where a regional tier of government plays an important role. "
    },
    {
      "Longitude": 8.4311,
      "Latitude": 49.3208,
      "City": "Speyer",
      "State/Territory": "Rhineland-Palatinate",
      "Country": "Germany",
      "Region": "Europe",
      "Name of Organization": "German Research Institute for Public Administration",
      "Website": "https://www.foev-speyer.de/",
      "Total Members": 8,
      "Year Founded": 1947,
      "About Us": "As a research institution that is unique in Germany, we examine public administration at all levels and show possibilities for further development and improvement. \"Research about and for public administration\" is our mission and our motto. That is why we aim for a balanced relationship between basic and application-oriented research - theory and practice belong together for us. We do not only present our results in the specialist discussion of the scientific community, We also ensure the transfer of new knowledge in constant dialogue with administrative practice. We offer public administrations practice-oriented scientific advice and support, we develop tailor-made solutions for their respective practical tasks and needs. We also orient our research on topics that are relevant to our partners are important in administrations, and we interlink current issues with long-term lines of development in states and societies."
    },
    {
      "Longitude": 9.057645,
      "Latitude": 48.521637,
      "City": "Tübingen",
      "State/Territory": "Baden-Württemberg",
      "Country": "Germany",
      "Region": "Europe",
      "Name of Organization": "Europäisches Zentrum für Föderalismusforschung",
      "Website": "https://uni-tuebingen.de/fakultaeten/wirtschafts-und-sozialwissenschaftliche-fakultaet/faecher/fachbereich-sozialwissenschaften/politikwissenschaft/forschung/europaeisches-zentrum-fuer-foederalismus-forschung/",
      "Total Members": 14,
      "Year Founded": 1993,
      "About Us": "he European Center for Research on Federalism Tübingen (EZFF), founded in 1993 by professors from various faculties and disciplines at the Eberhard Karls University of Tübingen, deals with various aspects of the territorial dimension of politics in Europe, including the EU (understood as a multi-level system): the importance of federal principles for the territorial structure of European states and the EU, as well as in decision-making processes in various policy areas; decentralization, regionalization and federalization processes in European countries; the role of regions and municipalities as actors in the respective states, in the EU system and in cross-border cooperation. "
    },
    {
      "Longitude": 77.216721,
      "Latitude": 28.6448,
      "City": "New Delhi",
      "State/Territory": "Delhi",
      "Country": "India",
      "Region": "Asia",
      "Name of Organization": "Centre for Multilevel Federalism",
      "Website": "http://www.issin.org/",
      "Total Members": 40,
      "Year Founded": 1979,
      "About Us": "The Institute of Social Sciences is dedicated to a systematic and scholarly study of contemporary social, political and economic issues from an inter-disciplinary perspective. The Institute makes its research findings and recommendations available to national and state governments, policy makers, UN organisations, international donor agencies, civil society organisations and workers unions so as to help them to make their decisions based on sound evidence. The Institute seeks to integrate academic rigour with the struggle for change, hence the motto of the organisation Integrating Research with Action."
    },
    {
      "Longitude": 77.216721,
      "Latitude": 28.6448,
      "City": "New Delhi",
      "State/Territory": "Delhi",
      "Country": "India",
      "Region": "Asia",
      "Name of Organization": "Centre for Federal Studies",
      "Website": "http://jamiahamdard.edu/Department/Deptindex.aspx?page=a&ItemID=mo&nDeptID=ks",
      "Total Members": 5,
      "Year Founded": 2016,
      "About Us": "This Centre is a member of the prestigious International Association of Centers for Federal Studies, exclusively dedicated to the studies, research, and teaching on dimensionalities of federal nation-building in multicultural comparative setting. The Centre's Mandate is: to develop as an exclusive knowledge resource centre and to grow as internationally acclaimed resource repository on various dimensions of federal nation-building in India and other multicultural and diverse polities of the world, particularly Euro-American and South Asian polities; to convert academic studies into pragmatic polieis; and to popularize federalism as a grand design of living together. The Centre has a unique knowledge repository on micro themes of Indian federation, democracy, polity, and society. The Centre has also developed its own data bank on select themes of Indian polity and society. The Knowledge resource of the Centre is being currently converted into online media for the access of national and international academia. "
    },
    {
      "Longitude": 11.3398,
      "Latitude": 46.4907,
      "City": "Bolzano",
      "State/Territory": "Trentino-Alto Adige",
      "Country": "Italy",
      "Region": "Europe",
      "Name of Organization": "Institute for Comparative Federalism of Eurac Research",
      "Website": "http://www.eurac.edu/en/pages/default.aspx",
      "Total Members": 437,
      "Year Founded": 1992,
      "About Us": "Eurac Research was founded in 1992 as an association under private law with just twelve members of staff undertaking research in the areas of Language and Law, Minorities and Autonomous Regions as well as the Alpine Environment. The center gradually expan​​ded its activities into new areas, attracted scientists from all over the world and introduced new structures. Today, almost 400 scientists from over 25 countries work here.​​ Our research is concerned with three major themes: regions fit for living in, a healthy society, and diversity as a life-enhancing factor. "
    },
    {
      "Longitude": 9.1895,
      "Latitude": 45.4643,
      "City": "Milan",
      "State/Territory": "Lombardy",
      "Country": "Italy",
      "Region": "Europe",
      "Name of Organization": "Centro Interuniversitario di Finanze Regionale e Locale",
      "Website": "https://centridiricerca.unicatt.it/cifrel_index.html",
      "Total Members": 24,
      "Year Founded": 1988,
      "About Us": "Cifrel was founded in 1988 by scholars belonging to several Italian universities to conduct applied researches on local and regional government. The Centre has administrative autonomy and is physically located in the premises of the Catholic University of Milano.  Currently, the members of the Centre are the University of Turin, the University of Brescia,  the University of Ferrara and the Catholic University of Milan. Cifrel is governed by a management committee, made up by representatives of the Universities involved, and by a Director. The current Director is Massimo Bordignon, a professor of the Catholic University. The centre produces both academic and policy oriented researches on key issues of public finance with a specific focus on multi-tiered level of government. Researchers associated to the Centre are faculty members of the four university with a keen interests in public economics and fiscal federalism. The centre has an history of close collaboration with a variety of institutions, both private and public, and had produced several reports to inform and evaluate policymaking, specifically concerning regional and local public finance in Italy and in many other countries. Beyond their activities as members of the Centre and as academic professors, Cifrel researchers are actively involved in the public debate on economic themes with their contribution disseminated through a variety of media (tv, newspapers, on-line)."
    },
    {
      "Longitude": 12.496366,
      "Latitude": 41.902782,
      "City": "Rome",
      "State/Territory": "Lazio",
      "Country": "Italy",
      "Region": "Europe",
      "Name of Organization": "Istituto di Studi sui Sistemi Regionali Federali e sulle Autonomie ''Massimo Severo Giannini''",
      "Website": "http://www.issirfa.cnr.it/",
      "Total Members": 35,
      "Year Founded": 1965,
      "About Us": "The Institute was established when the regions with ordinary statute began to exercise their functions; since then its activities have focused, with a series of research projects, on the effects of constitutional, administrative and financial reforms of regionalism and local government. The main research activities are: constitutional and administrative models of regionalism in Italy and in other countries; the distribution of functions and forms of inter-connection between the State, the regions and local authorities; the regions and legislative provisions of the European Community; the analysis of specific sectors of regional and local interest."
    },
    {
      "Longitude": 12.496366,
      "Latitude": 41.902782,
      "City": "Rome",
      "State/Territory": "Lazio",
      "Country": "Italy",
      "Region": "Europe",
      "Name of Organization": "Associazione Osservatorio Sul Federalismo e i Processi Di Governo",
      "Website": "https://www.federalismi.it/",
      "Total Members": 65,
      "Year Founded": 1906,
      "About Us": "Public journal of Italian, comparative, and European law. "
    },
    {
      "Longitude": 7.68682,
      "Latitude": 45.07049,
      "City": "Turin",
      "State/Territory": "Piedmont",
      "Country": "Italy",
      "Region": "Europe",
      "Name of Organization": "Centro Studi sul Federalismo",
      "Website": "http://www.csfederalismo.it/en/",
      "Total Members": 12,
      "Year Founded": 2011,
      "About Us": "The CSF aims to be a think tank that carries out activities of interdisciplinary research, documentation, information regarding domestic and supra-national federalism and developments in the area of regional and continental integration – first and foremost the European Union – and problems related to the world order and to the process of democratisation of the international system. The Centre’s mission is to promote the diffusion of knowledge in the field of studies on federalism, also to feed the public debate and the activity of decision-makers, confronted with demands for autonomy on the part of local government coupled with the forms of regional and world integration needed to govern global processes."
    },
    {
      "Longitude": -99.1332,
      "Latitude": 19.4326,
      "City": "Mexico City",
      "State/Territory": "Mexico",
      "Country": "Mexico",
      "Region": "North America",
      "Name of Organization": "Instituto Nacional para el Federalismo y el Desarrollo Municipal",
      "Website": "https://www.gob.mx/inafed",
      "Total Members": 8,
      "Year Founded": 1994,
      "About Us": "We are a decentralized administrative body of the Ministry of the Interior whose objective is to formulate, conduct and evaluate the policies and actions of the Federal Public Administration in matters of federalism, decentralization and municipal development. Our mission is to strengthen the institutional capacities of municipal governments based on the current legal framework, by offering solutions relevant to their needs, promoting their role as actors of their own development with full respect for their autonomy. "
    },
    {
      "Longitude": 85.324,
      "Latitude": 27.6644,
      "City": "Lalitpur",
      "State/Territory": "Bagmati Pradesh",
      "Country": "Nepal",
      "Region": "Asia",
      "Name of Organization": "Centre for Federalism Studies",
      "Website": "https://www.nasc.org.np/department-center/CFS",
      "Total Members": 6,
      "Year Founded": 1999,
      "About Us": "The scope and objectives for the Centre for Federalism Studies are to: design and deliver training courses on federal affairs to federal, provincial and local government including civil employees and representatives of citizens; engage in research and analysis on issues related to federalism; act as a resources center with excellence for consultation and advice on federal affairs to all levels of government; serve as one-stop federalism resource centre; and build training capacity on federalism that supports NASC's core training mandate. "
    },
    {
      "Longitude": 2.1734,
      "Latitude": 41.3851,
      "City": "Barcelona",
      "State/Territory": "Catalonia",
      "Country": "Spain",
      "Region": "Europe",
      "Name of Organization": "Institut d'Estudis de l’Autogovern",
      "Website": "https://presidencia.gencat.cat/ca/ambits_d_actuacio/desenvolupament_autogovern/institut-destudis-autogovern/",
      "Total Members": 13,
      "Year Founded": 1976,
      "About Us": "The Institut d'Estudis de l'Autogovern (IEA) is a research center linked to the Government of Catalonia specialized in the analysis of institutions, actors and collective decision-making processes in federal and regional democracies, as well as of the European Union and of secession processes. The Institute works with multidisciplinary teams (political, legal, economic, linguistic, cultural, etc.) both from a theoretical and comparative policy perspective, and from a perspective applied to specific cases. Their analysts are endowed with a vocation for international impact, as well as a practical impact on the ethical and functional improvement of democracies that have a multilevel territorial structure."
    },
    {
      "Longitude": -2.990057,
      "Latitude": 43.326702,
      "City": "Leioa",
      "State/Territory": "Biscay",
      "Country": "Spain",
      "Region": "Europe",
      "Name of Organization": "Ituna Center for Basque Economic Agreement and Fiscal Federalism Studies",
      "Website": "https://www.ituna.eus/en/about-the-center-and-networking/#:~:text=The%20main%20goal%20of%20the,currents%20of%20international%20fiscal%20federalism.",
      "Total Members": 16,
      "Year Founded": 1954,
      "About Us": "The main goal of the Ituna Center is to conduct research and promote scientific production related to the Basque Economic Agreement and the singular tax and financial system in the Basque Country in the context of the currents of international fiscal federalism. The Economic Agreement establishes an asymmetric model of tax and financial arrangements between the Spanish state and the Basque representative institutions, which have deep and extensive tax and financial self-government. Considered from the perspective of comparative Law, the Basque institutions are situated amongst the sub-state authorities with the greatest fiscal power in Europe. "
    },
    {
      "Longitude": -0.8773,
      "Latitude": 41.6561,
      "City": "Zaragoza",
      "State/Territory": "Aragon",
      "Country": "Spain",
      "Region": "Europe",
      "Name of Organization": "Foundation Manuel Giménez Abad for Parliamentary Studies and the Spanish State of Autonomies",
      "Website": "https://www.fundacionmgimenezabad.es/es",
      "Total Members": 8,
      "Year Founded": 1971,
      "About Us": "The Foundation aims, in accordance with the professional career of Manuel Giménez Abad, to contribute to the research, knowledge and dissemination of the parliamentary institution and of the model of territorial distribution of power represented by the autonomous state. The activities of the Foundation are structured in four fundamental areas, which synthesize its aims and its object of work: political and parliamentary studies; territorial organization; Iberoamerica; and studies on terrorism. "
    },
    {
      "Longitude": 7.1513,
      "Latitude": 46.8024,
      "City": "Fribourg",
      "State/Territory": "La Sarine",
      "Country": "Switzerland",
      "Region": "Europe",
      "Name of Organization": "Institute of Federalism",
      "Website": "https://www3.unifr.ch/federalism/en/",
      "Total Members": 18,
      "Year Founded": 1994,
      "About Us": "The Institute is a nationally and internationally renowned, politically independent centre of expertise in questions of state organisation. As such, it develops the academic foundations concerning the tasks of a state and the conflicts of interests the latter is exposed to: to fulfil state functions in line with the demands and in an economically sound manner; to act with democratic legitimacy; to cope with a pluralistic society and to respect the rights of individuals and minorities. The Institute's activities focus on the following areas: general theory of federal and decentralized state organisation; fundamentals and further development of the Swiss federal state; comparative federalism; democracy; fundamental and human rights; protection of minorities; conflict prevention and management; legisprudence; administrative law; and public procedural law. "
    },
    {
      "Longitude": 1.08,
      "Latitude": 51.279999,
      "City": "Canterbury",
      "State/Territory": "Kent",
      "Country": "United Kingdom",
      "Region": "Europe",
      "Name of Organization": "50 Shades of Federalism",
      "Website": "http://50shadesoffederalism.com/",
      "Total Members": 2,
      "Year Founded": 2017,
      "About Us": "50 Shades of Federalism is a project established in October 2017 at Canterbury Christ Church University to help inform debate about many issues related to the topic of ‘federalism’. Articles, written by some of the leading scholars and practitioners in the field, will be published on a regular basis. Having identified five main themes – Case Studies, Conflict Resolution, Diversity Management, Policies and Theory – the central aim of this project is to provide succinct, easy accessible, high quality research articles free of charge. The research articles will feature discussions on a number of abstract and historical issues, as well as illuminate some of the contemporary dynamics in debates on federalism. Given that the study of federalism straddles a variety of disciplines, we seek to pursue a multidisciplinary approach with contributions from politician scientists, theorists and constitutional lawyers, some of whom are leading scholars in the field."
    },
    {
      "Longitude": 0.9042,
      "Latitude": 51.8892,
      "City": "Colchester",
      "State/Territory": "Essex",
      "Country": "United Kingdom",
      "Region": "Europe",
      "Name of Organization": "ECPR Standing Group on Federalism and Regionalism of the European Consortium for Political Research",
      "Website": "https://standinggroups.ecpr.eu/fr/news/",
      "Total Members": 3,
      "Year Founded": 1912,
      "About Us": "The ECPR Standing Group on Federalism and Regionalism is the largest European scholarly network on the study of territorial politics. It brings together some 400 established and young scholars from across Europe and beyond. The Standing Group has a link with Regional and Federal Studies, the leading European specialist journal in the field. The basic aim is to bring together colleagues who are researching the fields of federalism, regionalism, decentralisation, multi-level governance and other territorial issues. The Standing Group helps to stimulate communication and research collaboration among members. "
    },
    {
      "Longitude": -77.10428,
      "Latitude": 38.88101,
      "City": "Arlington",
      "State/Territory": "Virginia",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "American Legislative Exchange Council",
      "Website": "https://www.alec.org/task-force/federalism-and-international-relations/",
      "Total Members": 54,
      "Year Founded": 1915,
      "About Us": "State legislators and their constituents are stakeholders in many of the most important national and international issues of the day. The members of the Federalism and International Relations Task Force believe in the power of free markets and limited government to propel economic growth in the United States and around the globe, and that these guiding principles are just as relevant overseas as they are in America. The Task Force brings together state legislators, policy experts and industry representatives to develop model policy to increase exports, safeguard intellectual property rights, promote the nation’s security, and restore the Constitutionally-designated balance of power between the states and the federal government. In order to capitalize on the specialized knowledge of the Task Force members we have formed three subcommittees: Federalism, Intellectual Property and National Security. Subcommittee Chairs are specialists in their respective disciplines having worked on these issues within their legislatures and/or in their careers outside the legislature."
    },
    {
      "Longitude": -84.38633,
      "Latitude": 33.753746,
      "City": "Atlanta",
      "State/Territory": "Georgia",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "Center on Federalism and Intersystemic Governance",
      "Website": "https://law.emory.edu/centers-and-programs/center-for-federalism-and-intersystemic-governance-conferences.html",
      "Total Members": 18,
      "Year Founded": 1984,
      "About Us": "The Center on Federalism and Intersystemic Governance seeks to explore the extraordinary rise of interest in—and debate over—federalism and intersystemic governance. Interest in the center thus springs from a shared view that the expansion of cross-jurisdictional interactions among courts, regulatory institutions, regulations, and regulators is an undeniable reality and is deserving of our close study. Domestically, internationally, and in transnational settings such as the European Union, one finds innumerable examples of federalist and interactive regulatory arrangements. Many real-world problems lie at the intersection of multiple regulatory regimes. Any viable regulatory approach, as such, must be constructed to operate within this web."
    },
    {
      "Longitude": -84.38633,
      "Latitude": 33.753746,
      "City": "Atlanta",
      "State/Territory": "Georgia",
      "Country": "United States",
      "Region": "North America ",
      "Name of Organization": "Southern Legislative Council",
      "Website": "https://www.slcatlanta.org/",
      "Total Members": 15,
      "Year Founded": 2015,
      "About Us": "The Council of State Governments is the nation’s only nonpartisan association of state officials serving all three branches of government in all 50 states and the U.S. territories. CSG is a region-based, national organization that promotes excellence in state government. CSG fosters the interstate exchange of insights and ideas to help state officials shape public policy, and it offers unparalleled regional, national and international opportunities to network, develop leaders, collaborate and create problem-solving partnerships. The mission of the Southern Office is to promote and strengthen intergovernmental cooperation among its 15 member states, predominantly through the programs and services provided by its Southern Legislative Conference. Legislative leadership, members and staff depend on the SLC to identify and analyze solutions for the most prevalent and unique state government policy issues facing Southern states. Member outreach in state capitols, leadership development an dstaff exchange programs, meetings, domestic and international delegation study tours, and policy fly-ins by the Southern Office support state policymakers and legislative staff in their work to build a stronger region. "
    },
    {
      "Longitude": -75.1196,
      "Latitude": 39.9259,
      "City": "Camden",
      "State/Territory": "New Jersey",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "Center for State Constitutional Studies",
      "Website": "https://statecon.camden.rutgers.edu/",
      "Total Members": 3,
      "Year Founded": 1947,
      "About Us": "The Center for State Constitutional Studies at Rutgers-Camden is an interdisciplinary institute dedicated to pormoting public understanding of American state constitutions and of sub-national constitutions in other federal systems through: research and publications; lectures and conferences; consultation services; and educational initiatives. "
    },
    {
      "Longitude": -75.6208,
      "Latitude": 40.6884,
      "City": "Easton",
      "State/Territory": "Pennsylvania",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "Center for the Study of Federalism at the Meyner Center for the Study of State & Local Government",
      "Website": "https://federalism.org/",
      "Total Members": 18,
      "Year Founded": 1959,
      "About Us": "The Center for the Study of Federalism is a nonpartisan, interdisciplinary research and education institution dedicated to supporting and advancing scholarship and public understanding of federal theories, principles, institutions, and processes as practical means of organizing power in free societies. "
    },
    {
      "Longitude": -88.0078,
      "Latitude": 41.88,
      "City": "Lombard",
      "State/Territory": "Illinois",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "The Council of State Governments-Midwest",
      "Website": "https://www.csgmidwest.org/",
      "Total Members": 16,
      "Year Founded": 2013,
      "About Us": "The Council of State Governments is the nation’s only nonpartisan association of state officials serving all three branches of government in all 50 states and the U.S. territories. CSG is a region-based, national organization that promotes excellence in state government. CSG fosters the interstate exchange of insights and ideas to help state officials shape public policy, and it offers unparalleled regional, national and international opportunities to network, develop leaders, collaborate and create problem-solving partnerships. CSG Midwest focuses on meeting the needs of state policymakers and leaders in the nation's heartland, including 11 Midwestern states: Illinois, Indiana, Iowa, Kansas, Michigan, Minnesota, Nebraska, North Dakota, Ohio, South Dakota and Wisconsin. In addition, four Canadian provinces —  Alberta, Manitoba, Ontario and Saskatchewan — are members or affiliate members of CSG Midwest's MIdwestern Legislative Conference. "
    },
    {
      "Longitude": -74.006,
      "Latitude": 40.7128,
      "City": "New York",
      "State/Territory": "New York",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "The Council of State Governments-East",
      "Website": "https://csg-erc.org/",
      "Total Members": 20,
      "Year Founded": 1985,
      "About Us": "The Council of State Governments champions excellence in state governments and for more than 85 years has convened state officials to consider how best to prepare for what’s next. If the states are laboratories of democracy, then CSG is the incubator for many of the ideas that move our states and nation forward. As a regional office of The Council of State Governments located in New York City, our purpose is to facilitate the exchange of ideas among state policymakers, business leaders, and the academic community throughout our 18-member jurisdictions. We foster discussions and collaboration among state officials to address the policy priorities unique to the Northeast, conduct leadership training programs, and advocate on the federal level for programs and policies beneficial to the region."
    },
    {
      "Longitude": -111.6946,
      "Latitude": 40.2969,
      "City": "Orem",
      "State/Territory": "Utah",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "Center for Constitutional Studies",
      "Website": "https://www.uvu.edu/ccs/",
      "Total Members": 6,
      "Year Founded": 1913,
      "About Us": "The Center for Constitutional Studies (CCS) at Utah Valley University was established in September 2011. The Center is a nonpartisan academic institute that promotes the instruction, study, and research of constitutionalism. We employ conferences, university curriculum, faculty scholarship, a robust research agenda, strategic partnerships, and K-12 initiatives to engage students, scholars, educators, leaders, and the public on important constitutional issues found at the intersection of political thought, public policy, religion, law, history, education, and economic. The Center prepares citizens with the broad understanding of thought and practices critical to the perpetuation of constitutional government, ordered liberty, and the rule of law."
    },
    {
      "Longitude": -121.4944,
      "Latitude": 38.5816,
      "City": "Sacramento",
      "State/Territory": "California",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "The Council of State Governments-West",
      "Website": "https://www.csgwest.org/about/AboutCSGWest.aspx",
      "Total Members": 18,
      "Year Founded": 1991,
      "About Us": "The Council of State Governments West (CSG West) is a non-profit, non-partisan organization that serves the western legislatures of Alaska, Arizona, California, Colorado, Hawaii, Idaho, Montana, Nevada, New Mexico, Oregon, Utah, Washington, Wyoming, the Pacific islands of American Samoa, the Commonwealth of Northern Mariana Islands, and Guam. Associate members include the Canadian provinces of Alberta and British Columbia. Through a variety of programs and services offered to legislators and legislative staff, CSG West facilitates regional cooperation, exchange of information and fosters the strengthening of legislative institutions among its 13 member states.  This includes policy forums, sharing of best practices, professional development training, international relations opportunities, publications and institutional linkages with other political entities in the West as well as nationally.  Such opportunities provide value to member states and create opportunities for lawmakers to develop lasting and insightful relationships with leaders in neighboring states."
    },
    {
      "Longitude": -77.0369,
      "Latitude": 38.9072,
      "City": "Washington, D.C.",
      "State/Territory": "District of Columbia ",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "The Federalist Society",
      "Website": "https://fedsoc.org/about-us",
      "Total Members": 43,
      "Year Founded": 1989,
      "About Us": "The Federalist Society for Law and Public Policy Studies is a group of conservatives and libertarians dedicated to reforming the current legal order. We are committed to the principles that the state exists to preserve freedom, that the separation of governmental powers is central to our Constitution, and that it is emphatically the province and duty of the judiciary to say what the law is, not what it should be. The Society seeks to promote awareness of these principles and to further their application through its activities. By providing a forum for legal experts of opposing views to interact with members of the legal profession, the judiciary, law students, academics, and the architects of public policy, the Society has redefined the terms of legal debate. Our expansion in membership, chapters, and program activity has been matched by the rapid growth of the Society's reputation and the quality and influence of our events. We have fostered a greater appreciation for the role of separation of powers; federalism; limited, constitutional government; and the rule of law in protecting individual freedom and traditional values. Overall, the Society's efforts are improving our present and future leaders' understanding of the principles underlying American law."
    },
    {
      "Longitude": -77.0369,
      "Latitude": 38.9072,
      "City": "Washington, D.C.",
      "State/Territory": "District of Columbia ",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "National Governors Association",
      "Website": "https://www.nga.org/",
      "Total Members": 55,
      "Year Founded": 1908,
      "About Us": "Founded in 1908, the National Governors Association is the voice of the leaders of 55 states, territories, and commonwealths. Our nation’s Governors are dedicated to leading bipartisan solutions that improve citizens’ lives through state government. Through NGA, Governors identify priority issues and deal with matters of public policy and governance at the state, national and global levels. NGA is the premier resource for not only Governors but also for their cabinet members, state policy experts, the U.S. Congress, and private enterprise. NGA offers an array of services to help collaboratively tell the states’ story. Thanks to decades of broad expertise, NGA teams are able to work side-by-side with state leaders to identify challenges, help Governors stay ahead of the curve and offer solutions before challenges become problems."
    },
    {
      "Longitude": -76.7075,
      "Latitude": 37.2707,
      "City": "Williamsburg",
      "State/Territory": "Virginia",
      "Country": "United States",
      "Region": "North America",
      "Name of Organization": "Conference of Chief Justices",
      "Website": "https://ccj.ncsc.org/",
      "Total Members": 58,
      "Year Founded": 2020,
      "About Us": "The Conference of Chief Justices (CCJ) was founded in 1949 to provide an opportunity for the highest judicial officers of the states to meet and discuss matters of importance in improving the administration of justice, rules and methods of procedure, and the organization and operation of state courts and judicial systems, and to make recommendations and bring about improvements on such matters."
    },
    {
      "Longitude": -77.0369,
      "Latitude": 38.9072,
      "City": "Washington, D.C.",
      "State/Territory": "District of Columbia ",
      "Country": "United States",
      "Region": "North America ",
      "Name of Organization": "National Conference of State Legislatures",
      "Website": "https://www.ncsl.org/",
      "Total Members": 42,
      "Year Founded": 1975,
      "About Us": "NCSL, founded in 1975, represents the legislatures in the states, territories and commonwealths of the U.S. Its mission is to advance the effectiveness, independence and integrity of legislatures and to foster interstate cooperation and facilitate the exchange of information among legislatures. NCSL also represents legislatures in dealing with the federal government, especially in support of state sovereignty and state flexibility and protection from unfunded federal mandates and unwarranted federal preemption. The conference promotes cooperation between state legislatures in the U.S. and those in other countries."
    },
    {
      "Longitude": -77.10428,
      "Latitude": 38.88101,
      "City": "Arlington",
      "State/Territory": "Virginia",
      "Country": "United States ",
      "Region": "North America",
      "Name of Organization": "State Policy Network",
      "Website": "https://spn.org/",
      "Total Members": 70,
      "Year Founded": 1970,
      "About Us": "State Policy Network’s vision is an America where all people can flourish because collaborative, entrepreneurial leaders have secured lasting social change, personal freedom, and economic opportunity at the state and local level. To accomplish our mission, State Policy Network supports the growth of a 50-state Network of state think tanks through programs and services that: advise and assist state-based leaders working to establish new think tanks; provide training, coaching, and strategic planning to empower state think tank leaders; connect state think tank leaders through peer networks, policy working groups, SPN's Annual Meeting, and online resources; defend the 50-state think tank network by sharing best legal practices, providing critical resources when members are attacked, and fighting organized assaults on free speech and citizen privacy."
    },
    {
      "Longitude": -73.5878,
      "Latitude": 45.5088,
      "City": "Montréal",
      "State/Territory": "Québec",
      "Country": "Canada",
      "Region": "North America",
      "Name of Organization": "Peter MacKell Chair in Federalism",
      "Website": "https://www.mcgill.ca/federalism/",
      "Total Members": 22,
      "Year Founded": 1915,
      "About Us": "The Peter MacKell Chair in Federalism aims to reflect on the foundations, potential, risks and concrete incarnations of the “federal phenomenon” understood broadly."
    }
  ];
  
  // export default data;